export default {
    // 棋子坐标数据
    domIdMap: new Map([
        ['redCheA', '#red-che-A'],
        ['redCheB', '#red-che-B'],
        ['redMaA', '#red-ma-A'],
        ['redMaB', '#red-ma-B'],
        ['redXiangA', '#red-xiang-A'],
        ['redXiangB', '#red-xiang-B'],
        ['redShiA', '#red-shi-A'],
        ['redShiB', '#red-shi-B'],
        ['redPaoA', '#red-pao-A'],
        ['redPaoB', '#red-pao-B'],
        ['redBingA', '#red-bing-A'],
        ['redBingB', '#red-bing-B'],
        ['redBingC', '#red-bing-C'],
        ['redBingD', '#red-bing-D'],
        ['redBingE', '#red-bing-E'],
        ['redShuai', '#red-shuai'],
        ['blackCheA', '#black-che-A'],
        ['blackCheB', '#black-che-B'],
        ['blackMaA', '#black-ma-A'],
        ['blackMaB', '#black-ma-B'],
        ['blackXiangA', '#black-xiang-A'],
        ['blackXiangB', '#black-xiang-B'],
        ['blackShiA', '#black-shi-A'],
        ['blackShiB', '#black-shi-B'],
        ['blackPaoA', '#black-pao-A'],
        ['blackPaoB', '#black-pao-B'],
        ['blackBingA', '#black-bing-A'],
        ['blackBingB', '#black-bing-B'],
        ['blackBingC', '#black-bing-C'],
        ['blackBingD', '#black-bing-D'],
        ['blackBingE', '#black-bing-E'],
        ['blackShuai', '#black-shuai']
    ]),
    currentPosition: {
        redCheA: [0, 9],
        redCheB: [8, 9],
        blackCheA: [0, 0],
        blackCheB: [8, 0],
        redMaA: [1, 9],
        redMaB: [7, 9],
        blackMaA: [1, 0],
        blackMaB: [7, 0],
        redXiangA: [2, 9],
        redXiangB: [6, 9],
        blackXiangA: [2, 0],
        blackXiangB: [6, 0],
        redShiA: [3, 9],
        redShiB: [5, 9],
        blackShiA: [3, 0],
        blackShiB: [5, 0],
        redShuai: [4, 9],
        blackShuai: [4, 0],
        redPaoA: [1, 7],
        redPaoB: [7, 7],
        blackPaoA: [1, 2],
        blackPaoB: [7, 2],
        redBingA: [0, 6],
        redBingB: [2, 6],
        redBingC: [4, 6],
        redBingD: [6, 6],
        redBingE: [8, 6],
        blackBingA: [0, 3],
        blackBingB: [2, 3],
        blackBingC: [4, 3],
        blackBingD: [6, 3],
        blackBingE: [8, 3],
    },
    // 玩家数据
    currentPlayer: 'red',
    redUsedSeconds: 0,
    blackUsedSeconds: 0,
    redTimer: null,
    blackTimer: null,
    // 选择数据
    beforeMoveX: 0, // 棋子移动前的像素坐标
    beforeMoveY: 0,
    clickX: 0, // 鼠标点击位置的像素坐标
    clickY: 0,
    step: false, // 记录场上是否有已经被选中的棋子
    twinklingChess: null, // 当前正选中棋子DOM缓存
    twinklingName: '', // 选中棋子的Id
    clickChessTimer: null, // 闪烁棋子的定时器
}